name: Deploy Portofolio

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [deploy-trigger]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # Install Node.js v16 if not installed
            if ! command -v node > /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
      
            # Install PM2 globally if not installed
            if ! command -v pm2 > /dev/null; then
              sudo npm install -g pm2
            fi
            cd portofolio-2021
            git pull origin master
            npm install --only=prod
            git status
            pm2 describe portofolio > /dev/null && pm2 restart portofolio || pm2 start --name portofolio npm -- start
