name: Deploy Portofolio

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [deploy-trigger]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd portofolio
            git pull origin master
            git status
            yarn install
            docker compose up --build -d
